/** Gruppierte Emojis für die Chat-Einfügen-Palette (Nachrichtentext). */
export const CHAT_EMOJI_SECTIONS = [
    {
        title: "Smileys & Stimmung",
        emojis: [
            "😀",
            "😃",
            "😄",
            "😁",
            "😅",
            "😂",
            "🤣",
            "🥲",
            "😊",
            "😇",
            "🙂",
            "😉",
            "😍",
            "🥰",
            "😘",
            "😋",
            "😛",
            "🤔",
            "😏",
            "😒",
            "😢",
            "😭",
            "😤",
            "😡",
            "🤯",
            "🥳",
            "😎",
            "🤩",
            "😴",
            "🤒",
            "🤝",
        ],
    },
    {
        title: "Gesten & Symbole",
        emojis: [
            "👍",
            "👎",
            "👏",
            "🙌",
            "🙏",
            "✌️",
            "🤞",
            "👋",
            "💪",
            "✨",
            "💯",
            "🔥",
            "⭐",
            "❤️",
            "💙",
            "💚",
            "💛",
            "🧡",
            "💜",
            "🖤",
            "💔",
            "❗",
            "❓",
            "✅",
            "❌",
        ],
    },
    {
        title: "Feier & Essen",
        emojis: [
            "🎉",
            "🎊",
            "🎁",
            "🎂",
            "🍕",
            "🍔",
            "☕",
            "🍺",
            "🥂",
            "🎵",
            "🎮",
            "⚽",
            "🏆",
        ],
    },
];
