/** Labels für Finanz-Kategorien (Schlüssel müssen zum Server `FinanceCategory` passen). */
export const FINANCE_CATEGORY_LABELS = {
    strom: "Strom",
    miete: "Miete",
    telefon: "Telefon (Festnetz)",
    handy: "Handy",
    internet: "Internet",
    mode: "Mode / Kleidung",
    essen: "Essen / Lebensmittel",
    bankgebuehren: "Bankgebühren",
    versicherung: "Versicherung (sonstige)",
    kredit: "Kredit / Raten",
    abos: "Abos & Mitgliedschaften",
    unterhalt: "Unterhalt",
    lohn: "Lohn / Gehalt",
    verkauf: "Verkauf / Einnahmen",
    gesundheit: "Gesundheit / Apotheke",
    auto: "Auto / Kfz",
    oeffentlich: "Rundfunk / öffentliche Abgaben",
    streaming: "Streaming / Medien",
    sparen: "Sparen / Anlagen",
    steuern: "Steuern",
    tanken: "Tanken / Kraftstoff",
    schule: "Schule / Ausbildung",
    tier: "Haustiere",
    reisen: "Reisen",
    geschenke: "Geschenke",
    haushalt: "Haushalt / Drogerie",
    sport: "Sport / Fitness",
    hobby: "Hobby / Freizeit",
    sonstiges: "Sonstiges",
};
export const FINANCE_CATEGORY_OPTIONS = Object.entries(FINANCE_CATEGORY_LABELS);
