import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Inbox } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
export function FriendRequestsCard({ requests, resolveUser, onAccept, onReject }) {
    return (_jsxs(Card, { id: "neonlink-friend-requests", className: "rounded-3xl border-white/10 bg-gradient-to-br from-white/[0.07] to-white/[0.02] text-white backdrop-blur-xl shadow-lg shadow-black/25 scroll-mt-4", children: [_jsx(CardHeader, { className: "pb-2", children: _jsxs(CardTitle, { className: "text-sm font-semibold flex items-center gap-2", children: [_jsx("span", { className: "text-base", "aria-hidden": true, children: "\uD83D\uDCE8" }), "Freundschaftsanfragen", requests.length > 0 ? (_jsx("span", { className: "ml-auto text-[10px] font-normal px-2 py-0.5 rounded-full bg-amber-500/25 text-amber-100 border border-amber-400/30", children: requests.length })) : null] }) }), _jsx(CardContent, { className: "space-y-2 pt-0 max-h-48 overflow-y-auto pr-1", children: requests.length === 0 ? (_jsxs("div", { className: "flex flex-col items-center justify-center py-6 text-center text-white/90", children: [_jsx(Inbox, { className: "h-8 w-8 mb-2 opacity-60" }), _jsx("p", { className: "text-xs font-medium", children: "Keine offenen Anfragen" })] })) : (requests.map((req) => {
                    const u = resolveUser(req.fromUserId);
                    const name = req.fromDisplayName ?? u?.displayName ?? "Unbekannt";
                    return (_jsxs("div", { className: "flex gap-2 items-center rounded-2xl border border-white/10 bg-black/25 p-2.5 hover:border-white/15 transition-colors", children: [_jsx(Avatar, { className: "h-10 w-10 shrink-0 overflow-hidden rounded-full border border-white/15", children: u?.avatarUrl ? (_jsx("img", { src: u.avatarUrl, alt: "", className: "h-full w-full object-cover" })) : (_jsx(AvatarFallback, { className: "flex h-full w-full items-center justify-center bg-white/10 text-xs", children: name.slice(0, 2).toUpperCase() })) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("div", { className: "text-sm font-semibold text-white truncate", children: name }), req.fromCategoryKeys?.length ? (_jsxs("div", { className: "text-[10px] text-cyan-200/90 mt-1", children: ["Zuordnung bei Absender: ", req.fromCategoryKeys.join(", ")] })) : null, _jsxs("div", { className: "flex gap-1.5 mt-2", children: [_jsx(Button, { type: "button", onClick: () => onAccept(req.id), className: "h-7 flex-1 rounded-lg border border-emerald-400/40 bg-emerald-500/25 text-emerald-50 hover:bg-emerald-500/35 text-[11px]", children: "Annehmen" }), _jsx(Button, { type: "button", onClick: () => onReject(req.id), className: "h-7 flex-1 rounded-lg border border-red-400/35 bg-red-500/20 text-red-100 hover:bg-red-500/30 text-[11px]", children: "Ablehnen" })] })] })] }, req.id));
                })) })] }));
}
