import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Copy, Link2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
export function InviteCodeCard({ friendCode, onCopyFriendCode, onRegenerateFriendCode, activeWorkspaceId, workspaceInviteCode, onWorkspaceInviteCodeChange, onJoinWorkspace, generatedWorkspaceInviteCode, onCreateWorkspaceInvite, copyHint, }) {
    const [regenBusy, setRegenBusy] = useState(false);
    return (_jsxs(Card, { className: "rounded-3xl border-white/10 bg-gradient-to-br from-white/[0.07] to-white/[0.02] text-white backdrop-blur-xl shadow-lg shadow-black/25", children: [_jsx(CardHeader, { className: "pb-2 space-y-0", children: _jsxs(CardTitle, { className: "text-sm font-semibold flex items-center gap-2 text-white/95", children: [_jsx("span", { className: "text-base", "aria-hidden": true, children: "\uD83D\uDD17" }), "Dein Freundescode"] }) }), _jsxs(CardContent, { className: "space-y-4 pt-0", children: [_jsxs("div", { className: "rounded-2xl border border-cyan-400/25 bg-cyan-500/10 px-3 py-3 shadow-inner shadow-black/20", children: [_jsx("div", { className: "text-[10px] uppercase tracking-wider text-cyan-200/70 mb-1.5", children: "Code teilen" }), _jsx("div", { className: "font-mono text-sm sm:text-base font-medium tracking-wide text-cyan-50 break-all", children: friendCode || "—" }), _jsxs("div", { className: "flex flex-wrap gap-2 mt-3", children: [_jsxs(Button, { type: "button", onClick: onCopyFriendCode, disabled: !friendCode, className: "h-8 rounded-xl border border-cyan-300/35 bg-cyan-500/20 text-cyan-50 hover:bg-cyan-500/30 text-xs gap-1.5 px-3", children: [_jsx(Copy, { className: "h-3.5 w-3.5" }), "Kopieren"] }), _jsxs(Button, { type: "button", disabled: regenBusy, onClick: () => {
                                            setRegenBusy(true);
                                            void onRegenerateFriendCode().finally(() => setRegenBusy(false));
                                        }, className: "h-8 rounded-xl border border-violet-400/35 bg-violet-500/20 text-violet-50 hover:bg-violet-500/30 text-xs gap-1.5 px-3", children: [_jsx(RefreshCw, { className: `h-3.5 w-3.5 ${regenBusy ? "animate-spin" : ""}` }), "Neu generieren"] })] }), copyHint ? _jsx("p", { className: "text-[11px] text-emerald-300/90 mt-2", children: copyHint }) : null] }), _jsxs("div", { className: "border-t border-white/10 pt-4 space-y-3", children: [_jsxs("div", { className: "flex items-center gap-2 text-white/80", children: [_jsx(Link2, { className: "h-4 w-4 text-white/50 shrink-0" }), _jsx("span", { className: "text-xs font-medium", children: "Team-Workspace" })] }), !activeWorkspaceId ? (_jsx("p", { className: "text-[11px] text-amber-200/80 leading-snug", children: "Workspace wird geladen \u2014 Team-Einladungen sind danach verf\u00FCgbar." })) : null, _jsx(Button, { type: "button", disabled: !activeWorkspaceId, onClick: () => onCreateWorkspaceInvite(), className: "w-full h-9 rounded-xl border border-violet-400/30 bg-violet-500/15 text-violet-100 hover:bg-violet-500/25 text-xs", children: "Neue Team-Einladung erzeugen" }), generatedWorkspaceInviteCode ? (_jsx("div", { className: "rounded-xl border border-violet-400/20 bg-violet-500/10 px-3 py-2 font-mono text-xs text-violet-100 break-all", children: generatedWorkspaceInviteCode })) : null, _jsx("label", { className: "sr-only", htmlFor: "friends-workspace-invite-input", children: "Workspace-Einladungscode" }), _jsx(Input, { id: "friends-workspace-invite-input", value: workspaceInviteCode, onChange: (e) => onWorkspaceInviteCodeChange(e.target.value), placeholder: "Team-Code (z. B. NL-ABC123)", className: "w-full min-w-0 bg-white/5 border-white/10 rounded-xl h-10 text-sm placeholder:text-white/40" }), _jsx(Button, { type: "button", onClick: () => onJoinWorkspace(), className: "w-full h-9 rounded-xl border border-emerald-400/35 bg-emerald-500/20 text-emerald-50 hover:bg-emerald-500/30 text-xs", children: "Mit Team-Code beitreten" })] })] })] }));
}
